### PR TITLE
Add behat scaffolding test.

### PR DESCRIPTION
**Pull request by mldk-tech**
#2

### CODE REVIEW

**Comment by amitaibu** [comment]
Yuri, can you please take it from here.

The test should be using api tag, not javascript

**Comment by mldk-tech** [comment]
I wanted to run it with selenium because of this I used javascript tag

**Comment by YuriGizra** [comment]
Pass:
selection_308
Fail:
selection_309

**Comment by YuriGizra** [comment]
@amitaibu @DavidKohav , ready for review.

**Comment by amitaibu** [comment]
Thanks, please merge squash.

@DavidKohav can you please enable it on Shoov.

**Comment by mldk-tech** [comment]
@amitaibu - Yes

**Comment by YuriGizra** [comment]
Merged manually.

**Comment by mldk-tech** [comment]
@amitaibu - I can't check the project in shoov

https://app.shoov.io/#/repos

The project on page number 3

**Pull request closed without merging**
